spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  profiles:
    active: dev

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: tlstjdtn321@gmail.com
    password: 'rflinyujgfwushfp'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:
  upload:
    path: /Users/mac/Downloads/학습관리시스템_프로젝트_시작소스_fastlms3/fastlms3/src/main/resources/static/images/